version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
     
  post_build:
    commands:
      - echo Build completed on `date`
      # copy the contents of /build to S3
      - aws s3 rm s3://myreactdemo --recursive
      - echo S3 bucket is cleared.
      - aws s3 cp dist s3://myreactdemo --recursive
      - echo Build completed on 'date'
      
